Fix Promote Release v5.10.2832
sourcegraph/deploy-sourcegraph-docker pull request #1123
Opened 2024-12-13 21:35 UTC by DaedalusG

This is a fixup PR to merge the v5.10.2832 release changes into main --
https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/1122

2024-12-13 21:40 UTC, jdpleiness commented on pure-docker/deploy-codeinsights-db.sh
> +  index.docker.io/sourcegraph/postgresql-16-codeinsights:insiders
This shouldn't be insiders in this case

2024-12-13 21:40 UTC, jdpleiness commented on pure-docker/deploy-codeintel-db.sh
> +  index.docker.io/sourcegraph/postgresql-16:insiders
Insiders here as well

2024-12-13 21:41 UTC, jdpleiness commented on pure-docker/deploy-pgsql.sh
> +  index.docker.io/sourcegraph/postgresql-16:insiders
Insiders here as well

2024-12-13 22:36 UTC, jdpleiness requested changes

2024-12-13 22:36 UTC, jdpleiness commented on docker-compose/db-only-migrate.docker-compose.yaml
> +    image: 'index.docker.io/sourcegraph/codeintel-db:5.10.2832@sha256:019bb4090f2bc20218887f5fd1bcfaa122ca090460f5803e1df4f6637947cb26'
This should be the postgresql-16 image

2024-12-13 22:44 UTC, Chickensoupwithrice commented on docker-compose/docker-compose.yaml
> +    image: 'index.docker.io/sourcegraph/postgres_exporter:5.10.2832@sha256:190eea7189d7831be9f04f13a47cfb19de9a1c1ac18739ac40d261f05c2b41aa'
I think this also needs to be postgresql-16-exporter?

2024-12-16 19:58 UTC, Chickensoupwithrice approved these changes

2025-01-09 21:44 UTC, closed without merging